spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.6.128:3306/babe
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.arms.ak47.pojo
  mapper-locations:
    classpath: mapper/*.xml

logging:
  config: ak47/logback.xml
  level:
    com.arms.ak47: error

