server:
  port: 8082
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.6.128:3306/babe
  thymeleaf:
    cache: false
  application:
    name: ak47

mybatis:
  type-aliases-package: com.arms.ak47.pojo
  mapper-locations:
    classpath: mapper/*.xml

logging:
  config: ak47/logback.xml
  level:
    com.arms.ak47: debug

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 10 # 服务失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 5 # 服务续约(renew)的间隔，默认为30秒
    instance-id: ${spring.application.name}:${server.port}